/* Core */
import { createSlice, type PayloadAction } from "@reduxjs/toolkit";

const initialState: VisitedComicsState = {
  visitedComics: [],
};

export const visitedComicsState = createSlice({
  name: "counter",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    doAddAction: (state, action: PayloadAction<VisitedComicsPayload>) => {
      console.log("doAddAction payload", action.payload);
      const item = action.payload;
      const index = state.visitedComics.findIndex((i) => i.id === item.id);
      console.log("index", index);
      if (index === -1) {
        state.visitedComics.unshift({
          id: item.id,
          chapterIds: [+item.chapterIds],
          chapterName: item.chapterName,
          image: item.image,
          name: item.name,
        });
      } else {
        if (state.visitedComics[index].chapterIds.includes(+item.chapterIds)) {
          return;
        } else {
          state.visitedComics[index] = {
            ...state.visitedComics[index],
            chapterIds: [
              ...state.visitedComics[index].chapterIds,
              +item.chapterIds,
            ],
            chapterName: item.chapterName,
            image: item.image,
            name: item.name,
          };
          const updatedItem = state.visitedComics.splice(index, 1)[0];
          state.visitedComics.unshift(updatedItem);
        }
      }
    },

    // Use the PayloadAction type to declare the contents of `action.payload`
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const { doAddAction } = visitedComicsState.actions;

/* Types */
export interface VisitedComicsState {
  visitedComics: {
    id: string;
    chapterIds: number[];
    chapterName: string;
    image: string;
    name: string;
  }[];
}

export interface VisitedComicsPayload {
  id: string;
  chapterIds: number;
  chapterName: string;
  image: string;
  name: string;
}

export default visitedComicsState.reducer;
